menu1:Menu.o scrolling.o animation.o CollisionBB.o
	gcc Menu.o scrolling.o animation.o CollisionBB.o -o menu1 -lSDL -lSDL_image -lSDL_mixer -g
Menu.o:Menu.c
	gcc -c Menu.c -lSDL -lSDL_image -lSDL_mixer -g
scrolling.o:scrolling.c
	gcc -c scrolling.c -lSDL -lSDL_image  -g
animation.o:animation.c
	gcc -c animation.c -lSDL -lSDL_image -g
CollisionBB.o:CollisionBB.c 
	gcc -c CollisionBB.c -lSDL -lSDL_image -g  
