menu1:Menu.o animation.o chrono.o collisionbb.o AffichageObj.o InitObjet.o collisiontc.o enigf.o init_entite.o pos_alea.o afficher_entite.o dep_va_x.o anim_entite_droite.o anim_entite_gauche.o
	gcc Menu.o  animation.o chrono.o collisionbb.o AffichageObj.o InitObjet.o collisiontc.o enigf.o init_entite.o pos_alea.o afficher_entite.o dep_va_x.o anim_entite_droite.o anim_entite_gauche.o -o menu1 -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf -lm -g
Menu.o:Menu.c
	gcc -c Menu.c -lSDL -lSDL_image -lSDL_mixer -g

animation.o:animation.c
	gcc -c animation.c -lSDL -lSDL_image -g
collisionbb.o:collisionbb.c 
	gcc -c collisionbb.c -lSDL -lSDL_image -g 
chrono.o:chrono.c 
	gcc -c chrono.c -lSDL -lSDL_image -lSDL_ttf -g  
InitObjet.o:InitObjet.c 
	gcc -c InitObjet.c -lSDL -lSDL_image -lSDL_ttf -g  
AffichageObj.o:AffichageObj.c 
	gcc -c AffichageObj.c -lSDL -lSDL_image -lSDL_ttf -g  
collisiontc.o:collisiontc.c 
	gcc -c collisiontc.c -lSDL -lSDL_image -lSDL_ttf -g   
enigf.o:enigf.c 
	gcc -c enigf.c -lSDL -lSDL_image -lSDL_ttf -g  
init_entite.o:init_entite.c
	gcc -c init_entite.c -lSDL -lSDL_image -g
pos_alea.o:pos_alea.c
	gcc -c pos_alea.c -lSDL -lSDL_image -g
afficher_entite.o:afficher_entite.c
	gcc -c afficher_entite.c -lSDL -lSDL_image -g


dep_va_x.o:dep_va_x.c
	gcc -c dep_va_x.c -lSDL -lSDL_image -g
anim_entite_droite.o:anim_entite_droite.c
	gcc -c anim_entite_droite.c -lSDL -lSDL_image -g
anim_entite_gauche.o:anim_entite_gauche.c
	gcc -c anim_entite_gauche.c -lSDL -lSDL_image -g
